var teclado = require("prompt-sync")();
var n1 = parseInt(teclado("Digite o n\u00FAmero a ser calculado"));
var n2 = parseInt(teclado("Digite o n\u00FAmero a ser calculado"));
var n3 = parseInt(teclado("Digite o n\u00FAmero a ser calculado"));
var n4 = parseInt(teclado("Digite o n\u00FAmero a ser calculado"));
var n5 = parseInt(teclado("Digite o n\u00FAmero a ser calculado"));
var n6 = parseInt(teclado("Digite o n\u00FAmero a ser calculado"));
var n7 = parseInt(teclado("Digite o n\u00FAmero a ser calculado"));
var n8 = parseInt(teclado("Digite o n\u00FAmero a ser calculado"));
var n9 = parseInt(teclado("Digite o n\u00FAmero a ser calculado"));
var n10 = parseInt(teclado("Digite o n\u00FAmero a ser calculado"));
var media = (n1 + n2 + n3 + n4 + n5 + n6 + n7 + n8 + n9 + n10) / 10;
console.log("A m\u00E9dia dos valores informados \u00E9 ".concat(media));
